### ISSUE TITLE
error on android 2.3.5 device

### ISSUE THREAD

**Issue by ouya99** [ANDLABS-Git/AndlabsAndroidUtils#2]
ads working fine on galaxy note 4.0.4 yet on my htc explorer (2.3.5) I get an exception.

09-26 18:20:15.671: D/View(7197): onTouchEvent: viewFlags: 0x18004001
09-26 18:20:15.671: D/View(7197): onTouchEvent: isFocusable: true, isFocusableInTouchMode: false, isFocused: false; focusTaken: false
09-26 18:20:15.671: I/[RevMob](7197): Loading Fullscreen
09-26 18:20:15.732: I/MillennialMediaSDK(7197): No next ad.
09-26 18:20:15.732: I/MillennialMediaSDK(7197): No incomplete downloads.
09-26 18:20:15.832: D/dalvikvm(7197): GC_CONCURRENT freed 525K, 44% free 3352K/5959K, external 0K/0K, paused 4ms+4ms
09-26 18:20:16.172: E/MillennialMediaSDK(7197): Error connecting:Connection to http://androidsdk.ads.mp.mydas.mobi refused
09-26 18:20:16.172: E/MillennialMediaSDK(7197): HTTP response is null.
09-26 18:20:16.172: D/AdUtils$3:436(7197): requestFailed(): mMedia not received
09-26 18:20:16.322: E/Chartboost(7197): Exception on http request: Connection to https://www.chartboost.com refused
09-26 18:20:16.322: D/AdUtils$4:479(7197): didFailToLoadInterstitial(): chartboost not received
09-26 18:20:18.734: I/[RevMob](7197): Problem with SSL. What is the version of your Android?
09-26 18:20:18.734: W/[RevMob](7197): RevMob did not answered as expected. (0)
09-26 18:20:18.734: D/AdUtils$1:316(7197): onRevMobAdNotReceived(): revMob not received
09-26 18:20:20.646: W/System.err(7197): com.adsdk.sdk.RequestException: Error in HTTP request
09-26 18:20:20.646: W/System.err(7197):     at com.adsdk.sdk.RequestAd.sendRequest(RequestAd.java:48)
09-26 18:20:20.646: W/System.err(7197):     at com.adsdk.sdk.AdManager$1.run(AdManager.java:135)
09-26 18:20:20.646: W/System.err(7197):     at java.lang.Thread.run(Thread.java:1027)
09-26 18:20:20.656: W/System.err(7197): Caused by: org.apache.http.conn.HttpHostConnectException: Connection to http://my.mobfox.com refused
09-26 18:20:20.656: W/System.err(7197):     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:178)
09-26 18:20:20.656: W/System.err(7197):     at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
09-26 18:20:20.656: W/System.err(7197):     at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
09-26 18:20:20.656: W/System.err(7197):     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:359)
09-26 18:20:20.656: W/System.err(7197):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
09-26 18:20:20.656: W/System.err(7197):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
09-26 18:20:20.656: W/System.err(7197):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
09-26 18:20:20.656: W/System.err(7197):     at com.adsdk.sdk.RequestAd.sendRequest(RequestAd.java:35)
09-26 18:20:20.656: W/System.err(7197):     ... 2 more
09-26 18:20:20.656: W/System.err(7197): Caused by: java.net.ConnectException: /50.23.145.4:80 - Connection refused
09-26 18:20:20.656: W/System.err(7197):     at org.apache.harmony.luni.net.PlainSocketImpl.connect(PlainSocketImpl.java:210)
09-26 18:20:20.666: W/System.err(7197):     at org.apache.harmony.luni.net.PlainSocketImpl.connect(PlainSocketImpl.java:440)
09-26 18:20:20.666: W/System.err(7197):     at java.net.Socket.connect(Socket.java:1013)
09-26 18:20:20.666: W/System.err(7197):     at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:119)
09-26 18:20:20.666: W/System.err(7197):     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:143)
09-26 18:20:20.666: W/System.err(7197):     ... 9 more
09-26 18:20:20.666: D/AdUtils$2:351(7197): noAdFound(): mobFox not received

maybe Inet connection is bad.. timeout problem? but browsing net works on the phone.

**Comment by ouya99** [comment]
Tested it on an android 2.3.3 emulator. works fine.. closing issue

**Comment by ouya99** [comment]
had to add wifi-permission for an emulator test (Manifest.xml)

<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"></uses-permission>
